INSERT INTO role(id, role_name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO role(id, role_name) VALUES (2, 'ROLE_USER');

INSERT INTO health_center(id, address, name) VALUES (1, 'Việt Nam', 'Global Domain');
INSERT INTO health_center(id, address, name) VALUES (2, 'Hải Châu, Đà Nẵng', 'Bệnh viện Đa khoa Đà Nẵng');

INSERT INTO mpi_user(id, full_name, password, user_name, role_id, health_center_id) VALUES (1, 'admin', '$2a$10$y5B4IoADd24253Ebi6cm/u.m/Pfz4L6HWpL/1rGs.QWac9uQlj/y.', 'admin', 1, 1);
INSERT INTO mpi_user(id, full_name, password, user_name, role_id, health_center_id) VALUES (2, 'user1', '$2a$10$y5B4IoADd24253Ebi6cm/u.m/Pfz4L6HWpL/1rGs.QWac9uQlj/y.', 'user1', 2, 2);
INSERT INTO mpi_user(id, full_name, password, user_name, role_id, health_center_id) VALUES (3, 'user2', '$2a$10$y5B4IoADd24253Ebi6cm/u.m/Pfz4L6HWpL/1rGs.QWac9uQlj/y.', 'user2', 2, 2);

INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (1, 'Thuật toán', 'ALGORITHM', '1');
INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (2, 'Điểm manual match', 'MANUAL_MATCH_SCORE', '60');
INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (3, 'Điểm auto match', 'AUTO_MATCH_SCORE', '80');

INSERT INTO field_weight(id, field, weight) VALUES (1, 0, 40);
INSERT INTO field_weight(id, field, weight) VALUES (2, 1, 0);
INSERT INTO field_weight(id, field, weight) VALUES (3, 2, 0);
INSERT INTO field_weight(id, field, weight) VALUES (4, 3, 20);
INSERT INTO field_weight(id, field, weight) VALUES (5, 4, 20);
INSERT INTO field_weight(id, field, weight) VALUES (6, 5, 20);

INSERT INTO province(id, code, name) VALUES (1, '001', 'Thành phố Hà Nội');
INSERT INTO province(id, code, name) VALUES (2, '002', 'Tỉnh Hà Giang');
INSERT INTO province(id, code, name) VALUES (3, '004', 'Tỉnh Cao Bằng');
INSERT INTO province(id, code, name) VALUES (4, '006', 'Tỉnh Bắc Kạn');
INSERT INTO province(id, code, name) VALUES (5, '008', 'Tỉnh Tuyên Quang');
INSERT INTO province(id, code, name) VALUES (6, '010', 'Tỉnh Lào Cai');
INSERT INTO province(id, code, name) VALUES (7, '011', 'Tỉnh Điện Biên');
INSERT INTO province(id, code, name) VALUES (8, '012', 'Tỉnh Lai Châu');
INSERT INTO province(id, code, name) VALUES (9, '014', 'Tỉnh Sơn La');
INSERT INTO province(id, code, name) VALUES (10, '015', 'Tỉnh Yên Bái');
INSERT INTO province(id, code, name) VALUES (11, '017', 'Tỉnh Hoà Bình');
INSERT INTO province(id, code, name) VALUES (12, '019', 'Tỉnh Thái Nguyên');
INSERT INTO province(id, code, name) VALUES (13, '020', 'Tỉnh Lạng Sơn');
INSERT INTO province(id, code, name) VALUES (14, '022', 'Tỉnh Quảng Ninh');
INSERT INTO province(id, code, name) VALUES (15, '024', 'Tỉnh Bắc Giang');
INSERT INTO province(id, code, name) VALUES (16, '025', 'Tỉnh Phú Thọ');
INSERT INTO province(id, code, name) VALUES (17, '026', 'Tỉnh Vĩnh Phúc');
INSERT INTO province(id, code, name) VALUES (18, '027', 'Tỉnh Bắc Ninh');
INSERT INTO province(id, code, name) VALUES (19, '030', 'Tỉnh Hải Dương');
INSERT INTO province(id, code, name) VALUES (20, '031', 'Thành phố Hải Phòng');
INSERT INTO province(id, code, name) VALUES (21, '033', 'Tỉnh Hưng Yên');
INSERT INTO province(id, code, name) VALUES (22, '034', 'Tỉnh Thái Bình');
INSERT INTO province(id, code, name) VALUES (23, '035', 'Tỉnh Hà Nam');
INSERT INTO province(id, code, name) VALUES (24, '036', 'Tỉnh Nam Định');
INSERT INTO province(id, code, name) VALUES (25, '037', 'Tỉnh Ninh Bình');
INSERT INTO province(id, code, name) VALUES (26, '038', 'Tỉnh Thanh Hóa');
INSERT INTO province(id, code, name) VALUES (27, '040', 'Tỉnh Nghệ An');
INSERT INTO province(id, code, name) VALUES (28, '042', 'Tỉnh Hà Tĩnh');
INSERT INTO province(id, code, name) VALUES (29, '044', 'Tỉnh Quảng Bình');
INSERT INTO province(id, code, name) VALUES (30, '045', 'Tỉnh Quảng Trị');
INSERT INTO province(id, code, name) VALUES (31, '046', 'Tỉnh Thừa Thiên Huế');
INSERT INTO province(id, code, name) VALUES (32, '048', 'Thành phố Đà Nẵng');
INSERT INTO province(id, code, name) VALUES (33, '049', 'Tỉnh Quảng Nam');
INSERT INTO province(id, code, name) VALUES (34, '051', 'Tỉnh Quảng Ngãi');
INSERT INTO province(id, code, name) VALUES (35, '052', 'Tỉnh Bình Định');
INSERT INTO province(id, code, name) VALUES (36, '054', 'Tỉnh Phú Yên');
INSERT INTO province(id, code, name) VALUES (37, '056', 'Tỉnh Khánh Hòa');
INSERT INTO province(id, code, name) VALUES (38, '058', 'Tỉnh Ninh Thuận');
INSERT INTO province(id, code, name) VALUES (39, '060', 'Tỉnh Bình Thuận');
INSERT INTO province(id, code, name) VALUES (40, '062', 'Tỉnh Kon Tum');
INSERT INTO province(id, code, name) VALUES (41, '064', 'Tỉnh Gia Lai');
INSERT INTO province(id, code, name) VALUES (42, '066', 'Tỉnh Đắk Lắk');
INSERT INTO province(id, code, name) VALUES (43, '067', 'Tỉnh Đắk Nông');
INSERT INTO province(id, code, name) VALUES (44, '068', 'Tỉnh Lâm Đồng');
INSERT INTO province(id, code, name) VALUES (45, '070', 'Tỉnh Bình Phước');
INSERT INTO province(id, code, name) VALUES (46, '072', 'Tỉnh Tây Ninh');
INSERT INTO province(id, code, name) VALUES (47, '074', 'Tỉnh Bình Dương');
INSERT INTO province(id, code, name) VALUES (48, '075', 'Tỉnh Đồng Nai');
INSERT INTO province(id, code, name) VALUES (49, '077', 'Tỉnh Bà Rịa - Vũng Tàu');
INSERT INTO province(id, code, name) VALUES (50, '079', 'Thành phố Hồ Chí Minh');
INSERT INTO province(id, code, name) VALUES (51, '080', 'Tỉnh Long An');
INSERT INTO province(id, code, name) VALUES (52, '082', 'Tỉnh Tiền Giang');
INSERT INTO province(id, code, name) VALUES (53, '083', 'Tỉnh Bến Tre');
INSERT INTO province(id, code, name) VALUES (54, '084', 'Tỉnh Trà Vinh');
INSERT INTO province(id, code, name) VALUES (55, '086', 'Tỉnh Vĩnh Long');
INSERT INTO province(id, code, name) VALUES (56, '087', 'Tỉnh Đồng Tháp');
INSERT INTO province(id, code, name) VALUES (57, '089', 'Tỉnh An Giang');
INSERT INTO province(id, code, name) VALUES (58, '091', 'Tỉnh Kiên Giang');
INSERT INTO province(id, code, name) VALUES (59, '092', 'Thành phố Cần Thơ');
INSERT INTO province(id, code, name) VALUES (60, '093', 'Tỉnh Hậu Giang');
INSERT INTO province(id, code, name) VALUES (61, '094', 'Tỉnh Sóc Trăng');
INSERT INTO province(id, code, name) VALUES (62, '095', 'Tỉnh Bạc Liêu');
INSERT INTO province(id, code, name) VALUES (63, '096', 'Tỉnh Cà Mau');


