INSERT INTO role(id, role_name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO role(id, role_name) VALUES (2, 'ROLE_USER');

INSERT INTO health_center(id, address, name) VALUES (1, 'Việt Nam', 'Global Domain');
INSERT INTO health_center(id, address, name) VALUES (2, 'Hải Châu, Đà Nẵng', 'Bệnh viện Đa khoa Đà Nẵng');

INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (1, 'Thuật toán', 'ALGORITHM', '1');
INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (2, 'Điểm manual match', 'MANUAL_MATCH_SCORE', '60');
INSERT INTO setting(id, description, mpi_key, mpi_value) VALUES (3, 'Điểm auto match', 'AUTO_MATCH_SCORE', '80');

INSERT INTO field_weight(id, field, weight) VALUES (1, 0, 40);
INSERT INTO field_weight(id, field, weight) VALUES (2, 1, 0);
INSERT INTO field_weight(id, field, weight) VALUES (3, 2, 0);
INSERT INTO field_weight(id, field, weight) VALUES (4, 3, 20);
INSERT INTO field_weight(id, field, weight) VALUES (5, 4, 20);
INSERT INTO field_weight(id, field, weight) VALUES (6, 5, 20);

INSERT INTO province(id, code, name) VALUES (1, '01', 'Thành phố Hà Nội');
INSERT INTO province(id, code, name) VALUES (2, '02', 'Tỉnh Hà Giang');
INSERT INTO province(id, code, name) VALUES (3, '04', 'Tỉnh Cao Bằng');
INSERT INTO province(id, code, name) VALUES (4, '06', 'Tỉnh Bắc Kạn');
INSERT INTO province(id, code, name) VALUES (5, '08', 'Tỉnh Tuyên Quang');
INSERT INTO province(id, code, name) VALUES (6, '10', 'Tỉnh Lào Cai');
INSERT INTO province(id, code, name) VALUES (7, '11', 'Tỉnh Điện Biên');
INSERT INTO province(id, code, name) VALUES (8, '12', 'Tỉnh Lai Châu');
INSERT INTO province(id, code, name) VALUES (9, '14', 'Tỉnh Sơn La');
INSERT INTO province(id, code, name) VALUES (10, '15', 'Tỉnh Yên Bái');
INSERT INTO province(id, code, name) VALUES (11, '17', 'Tỉnh Hoà Bình');
INSERT INTO province(id, code, name) VALUES (12, '19', 'Tỉnh Thái Nguyên');
INSERT INTO province(id, code, name) VALUES (13, '20', 'Tỉnh Lạng Sơn');
INSERT INTO province(id, code, name) VALUES (14, '22', 'Tỉnh Quảng Ninh');
INSERT INTO province(id, code, name) VALUES (15, '24', 'Tỉnh Bắc Giang');
INSERT INTO province(id, code, name) VALUES (16, '25', 'Tỉnh Phú Thọ');
INSERT INTO province(id, code, name) VALUES (17, '26', 'Tỉnh Vĩnh Phúc');
INSERT INTO province(id, code, name) VALUES (18, '27', 'Tỉnh Bắc Ninh');
INSERT INTO province(id, code, name) VALUES (19, '30', 'Tỉnh Hải Dương');
INSERT INTO province(id, code, name) VALUES (20, '31', 'Thành phố Hải Phòng');
INSERT INTO province(id, code, name) VALUES (21, '33', 'Tỉnh Hưng Yên');
INSERT INTO province(id, code, name) VALUES (22, '34', 'Tỉnh Thái Bình');
INSERT INTO province(id, code, name) VALUES (23, '35', 'Tỉnh Hà Nam');
INSERT INTO province(id, code, name) VALUES (24, '36', 'Tỉnh Nam Định');
INSERT INTO province(id, code, name) VALUES (25, '37', 'Tỉnh Ninh Bình');
INSERT INTO province(id, code, name) VALUES (26, '38', 'Tỉnh Thanh Hóa');
INSERT INTO province(id, code, name) VALUES (27, '40', 'Tỉnh Nghệ An');
INSERT INTO province(id, code, name) VALUES (28, '42', 'Tỉnh Hà Tĩnh');
INSERT INTO province(id, code, name) VALUES (29, '44', 'Tỉnh Quảng Bình');
INSERT INTO province(id, code, name) VALUES (30, '45', 'Tỉnh Quảng Trị');
INSERT INTO province(id, code, name) VALUES (31, '46', 'Tỉnh Thừa Thiên Huế');
INSERT INTO province(id, code, name) VALUES (32, '48', 'Thành phố Đà Nẵng');
INSERT INTO province(id, code, name) VALUES (33, '49', 'Tỉnh Quảng Nam');
INSERT INTO province(id, code, name) VALUES (34, '51', 'Tỉnh Quảng Ngãi');
INSERT INTO province(id, code, name) VALUES (35, '52', 'Tỉnh Bình Định');
INSERT INTO province(id, code, name) VALUES (36, '54', 'Tỉnh Phú Yên');
INSERT INTO province(id, code, name) VALUES (37, '56', 'Tỉnh Khánh Hòa');
INSERT INTO province(id, code, name) VALUES (38, '58', 'Tỉnh Ninh Thuận');
INSERT INTO province(id, code, name) VALUES (39, '60', 'Tỉnh Bình Thuận');
INSERT INTO province(id, code, name) VALUES (40, '62', 'Tỉnh Kon Tum');
INSERT INTO province(id, code, name) VALUES (41, '64', 'Tỉnh Gia Lai');
INSERT INTO province(id, code, name) VALUES (42, '66', 'Tỉnh Đắk Lắk');
INSERT INTO province(id, code, name) VALUES (43, '67', 'Tỉnh Đắk Nông');
INSERT INTO province(id, code, name) VALUES (44, '68', 'Tỉnh Lâm Đồng');
INSERT INTO province(id, code, name) VALUES (45, '70', 'Tỉnh Bình Phước');
INSERT INTO province(id, code, name) VALUES (46, '72', 'Tỉnh Tây Ninh');
INSERT INTO province(id, code, name) VALUES (47, '74', 'Tỉnh Bình Dương');
INSERT INTO province(id, code, name) VALUES (48, '75', 'Tỉnh Đồng Nai');
INSERT INTO province(id, code, name) VALUES (49, '77', 'Tỉnh Bà Rịa - Vũng Tàu');
INSERT INTO province(id, code, name) VALUES (50, '79', 'Thành phố Hồ Chí Minh');
INSERT INTO province(id, code, name) VALUES (51, '80', 'Tỉnh Long An');
INSERT INTO province(id, code, name) VALUES (52, '82', 'Tỉnh Tiền Giang');
INSERT INTO province(id, code, name) VALUES (53, '83', 'Tỉnh Bến Tre');
INSERT INTO province(id, code, name) VALUES (54, '84', 'Tỉnh Trà Vinh');
INSERT INTO province(id, code, name) VALUES (55, '86', 'Tỉnh Vĩnh Long');
INSERT INTO province(id, code, name) VALUES (56, '87', 'Tỉnh Đồng Tháp');
INSERT INTO province(id, code, name) VALUES (57, '89', 'Tỉnh An Giang');
INSERT INTO province(id, code, name) VALUES (58, '91', 'Tỉnh Kiên Giang');
INSERT INTO province(id, code, name) VALUES (59, '92', 'Thành phố Cần Thơ');
INSERT INTO province(id, code, name) VALUES (60, '93', 'Tỉnh Hậu Giang');
INSERT INTO province(id, code, name) VALUES (61, '94', 'Tỉnh Sóc Trăng');
INSERT INTO province(id, code, name) VALUES (62, '95', 'Tỉnh Bạc Liêu');
INSERT INTO province(id, code, name) VALUES (63, '96', 'Tỉnh Cà Mau');

